
spring:

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      #      host: 192.168.200.128
      host: 127.0.0.1
      port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.Mysql.Entity
  configuration:
    map-underscore-to-camel-case: true



